---
driver:
  name: vagrant
  provision: true
  vagrantfiles:
    - .kitchen.provision.rb

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-18.04-ci
    driver:
      name: dokken
      image: dokken/ubuntu-18.04
      provision: true
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
    provisioner:
      name: dokken
      product_name: chef
      product_version: 14
      data_bags_path: test/data_bags
      chef_license: accept
    transport:
      name: dokken

suites:
  - name: accounts
    run_list:
      - recipe[accounts::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: apache
    run_list:
      - recipe[apache::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: apt
    run_list:
      - recipe[apt::default]
  - name: bind
    run_list:
      - recipe[bind::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: blogs
    run_list:
      - recipe[accounts::default]
      - recipe[blogs::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: forum
    run_list:
      - recipe[accounts::default]
      - role[forum]
    excludes: ["ubuntu-18.04-ci"]
  - name: letsencrypt
    run_list:
      - recipe[accounts::default]
      - recipe[apt::default]
      - role[letsencrypt]
    attributes:
      apt:
        sources:
          - openstreetmap
    excludes: ["ubuntu-18.04-ci"]
  - name: munin
    run_list:
      - recipe[munin::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: munin-server
    run_list:
      - recipe[munin::server]
    excludes: ["ubuntu-18.04-ci"]
  - name: mysql
    run_list:
      - recipe[mysql::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: networking
    run_list:
      - recipe[networking::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: otrs
    run_list:
      - recipe[accounts::default]
      - recipe[chef::default]
      - role[otrs]
    excludes: ["ubuntu-18.04-ci"]
  - name: python
    run_list:
      - recipe[python::default]
    excludes: ["ubuntu-18.04-ci"]
  - name: tools
    run_list:
      - recipe[tools::default]
    excludes: ["ubuntu-18.04-ci"]
